### ISSUE TITLE
Tab IMDB Online not formatting correctly

### ISSUE THREAD

**Issue by copperhead57** [andig/videodb#100]
Tab 'imdb online' not applying css to html returned from imdb.
![capture](https://user-images.githubusercontent.com/8018102/40867756-2f8d2d58-664a-11e8-84ae-90c7029722c3.PNG)

**Comment by copperhead57** [comment]
code change to fix this.  I don't know GitHub well enough to supply a patch but here is code changes.
<br>
trace.php <br>
Line 56 <br>
     // fully qualified?<br>
     if (preg_match("/^http:\/\//", $url)) return $url;<br>
+    if (preg_match("/^https:\/\//", $url)) return $url;<br>
+    if (preg_match("/http:\/\//", $url)) return $url;<br>
+    if (preg_match("/https:\/\//", $url)) return $url;<br>

**Comment by andig** [comment]
Fixed via c9986ef063f6aa10ffc1cf796c8f0ffbbd0ebe83, thanks!
