### ISSUE TITLE
Engine -> OFDB Scraper - Cover URL doesn't get added

### ISSUE THREAD

**Issue by rocKay82** [andig/videodb#107]
By using the OFDB Scraper mode the Cover URL doesn't get added

**Comment by rocKay82** [comment]
Fixed it myself, works as follows:
CoverUrl has to be adjusted in engines>>ofdbscraper.php
I'm not very familiar with github. Maybe somebody likes to add it to the regarding file.

    // Cover URL
    if (preg_match('#<img src="(images/film/na.gif)"#i', $resp['data'], $ary))
    {
        $data['coverurl'] = $ofdbscraperServer.'/'.trim($ary[1]);
    }
    else if (preg_match('#<img src="(images/film/.*?\.jpg)"#i', $resp['data'], $ary))
    {
        $data['coverurl'] = $ofdbscraperServer.'/'.trim($ary[1]);
    }

**Comment by rocKay82** [comment]
Still issue in last version if cover image is another format like png. So new fix (2 versions):

```
    // Cover URL v1 maybe more safe (edited by rocKay82)
    if (preg_match('#<img src="images/film/.*?\.(jpg|gif|png)"#i', $resp['data'], $ary2))
    {
    	if (preg_match('#<img src="(images/film/.*?\.)#i', $resp['data'], $ary))
    	{
      	  $data['coverurl'] = $ofdbscraperServer.'/'.trim($ary[1]).trim($ary2[1]);
    	}
  	}
  	*/
  	
  	// Cover URL v2 (edited by rocKay82)
  	if (preg_match('#<img src="(images/film/.*?)"#i', $resp['data'], $ary))
    {
    	$data['coverurl'] = $ofdbscraperServer.'/'.trim($ary[1]);
    }
```

**Comment by johanneskonst** [comment]
Thank you for the examples and code, continuing in #106
