### ISSUE TITLE
Import from HDD Error

### ISSUE THREAD

**Issue by Ice81** [andig/videodb#113]
Hi there,
I try to import my movies from my  Qnap. VideoDB is also on Qnap. I got this error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ' video_height = , filedate =' at line 7 
INSERT videodata SET filename='/share/Multimedia/Filme/23 – Nichts ist so wie es scheint.avi', mediatype='51', title='23 – Nichts ist so wie es scheint', filesize=733345792, audio_codec = '', video_codec = '', video_width = , video_height = , filedate = FROM_UNIXTIME(1203431768)

I don´t understand what's the matter.

has anyone the same problem and maybe an solution ?

**Comment by kec2** [comment]
Do you use the latest version of VideoDB?
How do I replicate this error?

**Comment by Ice81** [comment]
I have the last version (4.0)
I use a QNAP TS-419 P, I use a local SQL database on the NAS.
My Movies are under the directory: /share/Multimedia/Filme
My videoadd.php Config:
`//NOTE : as a minimum change the following movie_dirs variable to point to a movi directory $movie_dirs = array("/moviedir1","/moviedir2);
$movie_dirs = array("/share/Multimedia/Filme");`

I hope thats the Information they you need.
Thanks for Help and sorry for my bad school english :-)

**Comment by kec2** [comment]
Latest version is 4.1. But there has been any changes to contribute/videoadd.php in a very long time.

Do you have mplayer install?
Could you try to run this command and report back:
mplayer -vo null -ao null -frames 0 -identify "/share/Multimedia/Filme/23 – Nichts ist so wie es scheint.avi"

There are a few thing in contribute/videoadd.php that needs to be fixed before it works again.
There are deprecated statements, missing audio and video codec.

I'm not sure if mplayer is the best tool to extract metadata from media file.
I'll try to come up with a fix.

**Comment by Ice81** [comment]
Ok, I´ve upgrade to 4.1 at this moment.
I try the command and I don´t have Mplayer on my Qnap.
so I will compile Mplayer on my Qnap and will try again.
