### ISSUE TITLE
php 7.2 each and create_function deprecated

### ISSUE THREAD

**Issue by NF13** [andig/videodb#121]
See exceptions:

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /lib/smarty/sysplugins/smarty_internal_compilebase.php on line 75

Deprecated: Function create_function() is deprecated in /core/functions.core.php on line 280

Deprecated: Function create_function() is deprecated in /core/template.php on line 299

See also

https://www.php.net/manual/function.create-function.php
https://www.php.net/manual/function.each.php

**Comment by andig** [comment]
I would be happy to accept a pr- but I‘m no longer actively maintaining the codebase.

**Comment by NF13** [comment]
@andig no problem see #122
