### ISSUE TITLE
Imdb data fetching doesnt work correctly anymore

### ISSUE THREAD

**Issue by dan-elevate** [andig/videodb#130]
hello

Since recently I have issues fetching data from IMDB:

Cover Image
Director
Country
Rating

and possibly others are not being fetched anymore. Actor data works as well as titles etc.

if you could fix this, would be great!

thank you!

**Comment by kec2** [comment]
I can take a look during this week.

Which movie(s) are showing these problems?

**Comment by dan-elevate** [comment]
hey! Thanks!!!

for example: imdb:11356922

or imdb:11525644

**Comment by jbjoret** [comment]
Same for me. Something has changed in the data structure.

**Comment by kec2** [comment]
I have made the fix in my fork but I can't figure out how to make a pull request for that one file only.
https://github.com/kec2/videodb/blob/master/engines/imdb.php

**Comment by dan-elevate** [comment]
thxxx it works!

**Comment by copperhead57** [comment]
I have lost the add movie and show movie buttons.
anyone else having this problem

**Comment by kec2** [comment]
Where should these buttons be?

**Comment by copperhead57** [comment]
Should be near the title, are added in the trace.php file.
I suspect they are being overridden by JavaScript.


-------- Original message --------
From: kec2 ***@***.***>
Date: 11/7/21 3:25 pm (GMT+10:00)
To: andig/videodb ***@***.***>
Cc: Paul copperhead ***@***.***>, Comment ***@***.***>
Subject: Re: [andig/videodb] Imdb data fetching doesnt work correctly anymore (#130)


Where should these buttons be?

**Comment by kec2** [comment]
Okay, can you make another issue for this problem?

On July 11, 2021 7:56:56 AM GMT+02:00, Paul copperhead ***@***.***> wrote:
>Should be near the title, are added in the trace.php file.>
>I suspect they are being overridden by JavaScript.>
>>
>>
>-------- Original message -------->
>From: kec2 ***@***.***>>
>Date: 11/7/21 3:25 pm (GMT+10:00)>
>To: andig/videodb ***@***.***>>
>Cc: Paul copperhead ***@***.***>, Comment ***@***.***>>
>Subject: Re: [andig/videodb] Imdb data fetching doesnt work correctly
>anymore (#130)>
>>
>>
>Where should these buttons be?>
>>
>—>
>You are receiving this because you commented.>
>Reply to this email directly, view it on
>GitHub<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandig%2Fvideodb%2Fissues%2F130%23issuecomment-877743806&data=04%7C01%7C%7C91ff7f9a9062413cef8f08d9442c4080%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637615779112456945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZFfRN76QwPzzGowjlB9Amq9nE5Z50c%2FutQKzAcPvCTY%3D&reserved=0>,
>or
>unsubscribe<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB5FRNUGG4HKOBAUUD7W6P3TXETLLANCNFSM47ZDAUPA&data=04%7C01%7C%7C91ff7f9a9062413cef8f08d9442c4080%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637615779112466938%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tKx88Foi0M%2F7mOOVTu3bAARZeZMPkuaQtIOYdp70h8g%3D&reserved=0>.>
>>
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/andig/videodb/issues/130#issuecomment-877746346

Hilsen
Klaus Christiansen

**Comment by dan-elevate** [comment]
hello!

I discovered that one more thing is missing in the fetching:

The Genres,,
example: imdb:8847712

**Comment by kec2** [comment]
Okay I'll into it.

On July 13, 2021 7:59:37 PM GMT+02:00, dan-elevate ***@***.***> wrote:
>hello!
>
>I discovered that one more thing is missing in the fetching:
>
>The Genres,,
>example: imdb:8847712
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/videodb/issues/130#issuecomment-879288620

Hilsen
Klaus Christiansen

**Comment by dan-elevate** [comment]
hello

unfortunately as of now it seems like 

- COVER IMAGES
- YEAR

is missing again when fetching from imdb

would be greatly appreciated if there is a fix for this
thankx!!!

**Comment by dan-elevate** [comment]
many thanks for fixing that!!!!

**Comment by dan-elevate** [comment]
Hello!
Unfortunately, grabbing the main movie poster image from imdb seems to not work currently.
example: https://www.imdb.com/title/tt0083590/

**Comment by dan-elevate** [comment]
ping!
please help!

**Comment by dan-elevate** [comment]
hello!
again there is problems fetching data!

the search for a title doeesnt work anymore..


please help

**Comment by kec2** [comment]
Hey

I'll take a look at it.

Regards kec2

On 20 October 2022 12.39.25 CEST, dan-elevate ***@***.***> wrote:
>hello!
>again there is problems fetching data!
>
>the search for a title doeesnt work anymore..
>
>
>please help
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/videodb/issues/130#issuecomment-1285312344
>You are receiving this because you commented.
>
>Message ID: ***@***.***>
Hilsen
Klaus Christiansen

**Comment by dan-elevate** [comment]
thank you very much and please let me know of any updates!

**Comment by dan-elevate** [comment]
actually, I just tested it again - and it works now. weird, but good news

**Comment by dan-elevate** [comment]
an no it doesnt, because as soon as there is a blank space in the title, it doesnt work. I search for "Rosa Parks" - no result.. I search for "Traumazone" and I get the result and fetching works

**Comment by kec42** [comment]
@dan-elevate 
Can we make another ticket for this search issue?

**Comment by johanneskonst** [comment]
As of now fetching details works. Closing this issue as resolved.
If the need arises please open a new issue. Thanks!
