### ISSUE TITLE
imdbonline-add movie and show movie buttons missing

### ISSUE THREAD

**Issue by copperhead57** [andig/videodb#131]
when displaying a movie/series etc in imdbonline, the add movie and show movie buttons are not displaying. they normally appear near the title

**Comment by copperhead57** [comment]
in trace.php line 319 amended for new h1 code.
however buttons still not appearing, suspect javascript is removing the code.
have noticed buttons flash appear then disappear.

**Comment by kec2** [comment]
@copperhead57 Do you know that is going on in the function fixup_HTML()?

I can't figure out what these regex:
(<a\s+[^>]*?href\s*=\s*(\"|'))([^>]*?)(\\2[^>]*?>)(.*?)(<\/a\s*>)
(<a\s+[^>]*?href\s*=\s*())([\d\w\.\/\+\%-:=&_]+)(\s*[^>]*?>)(.*?)(<\/a\s*>)
are suppose to match.

**Comment by copperhead57** [comment]
@kec2 
I think that code adds the buttons to some of the old style pages, which still works.
example type 2012 in search field then click the magnifying glass and the buttons will appear.
 
I have a testing fix in my 'merge_test' branch. Which includes fix by kec42 to issue 130.

the fix adds code to the javascript, the new imdb layout uses webpack which seems to override all my attempts to insert native htlm code into the page.

**Comment by copperhead57** [comment]
@kec2 
further changes pushed into my branch 'merge_test'.
Would be good if people can test this.
cheers Paul.

**Comment by kec2** [comment]
I can take a look later. 
By the way kec42 is also me.

**Comment by copperhead57** [comment]
have found another twist where imdb is dynamically changing function names in the JavaScript.
working on a solution

**Comment by copperhead57** [comment]
new version has been included in merge_test branch to handle dynamically changing function names in the JavaScript.

**Comment by kec2** [comment]
Nice work. 
I'll look at it when I get back from vacation.

On July 22, 2021 8:14:18 AM GMT+02:00, Paul copperhead ***@***.***> wrote:
>new version has been included in merge_test branch to handle
>dynamically changing function names in the JavaScript.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/andig/videodb/issues/131#issuecomment-884679410

Hilsen
Klaus Christiansen

**Comment by copperhead57** [comment]
new version of merge_test branch to handle issue with title number being deleted from path in function get_base() randomly.
