### ISSUE TITLE
Automatic Title Search Bug (when using empty space in title)

### ISSUE THREAD

**Issue by dan-elevate** [andig/videodb#139]
As soon as there is a blank space in the title, the search doesnt work. 

I search for "Rosa Parks" - no result.. 

I search for "Traumazone" and I get the result and fetching works

**Comment by kec42** [comment]
I don't think It's because of the empty space.
But it is very weird. I have Simmerly problems with King Kong

Works:
Rosa parks
Rosa parkS
Rosa paRKS
Rosa PARKS

Does not work
rosa parks
Rosa Parks
Rosa parKS
Rosa pARKS

**Comment by johanneskonst** [comment]
This was fixed by #140 and #151
