### ISSUE TITLE
Make the display of actors an toggle-able option.

### ISSUE THREAD

**Issue by johanneskonst** [andig/videodb#147]
Since the show?id=n page can be quite heavy when there are a lot of actors, and that list is not often something i want to see when viewing details, make it an option-able bit by means of a "Show Actors" button.

I already have a working bit of code but would like to add a configuration option for it as well, will provide PR at later date

**Comment by andig** [comment]
Or better: load aync!

**Comment by johanneskonst** [comment]
Async through JavaScript would also be nice but the current support for that inside videoDB is a bit too haphazard to my liking. Would like to test and discuss options for that to be added at a later date...
Also, since we're october, a hacktoberfest-accepted label added to my PR's would be nice ;-)
