### ISSUE TITLE
hrtpclient failure message not displayed retrieving actor images

### ISSUE THREAD

**Issue by copperhead57** [andig/videodb#168]
When retrieving actor images and httpclient encounters an error  (eg 404 not found) the errorpage function in functions.php is jumped to.
As Videodb has already displayed details of the movie and is unable to display the error encountered and will display the broken image  icon on the page.

Possible solution to at least access the message if need to solve issues is to write to a log file.

**Comment by johanneskonst** [comment]
Little addendum to my comment on pr #169 :
The actor image should either be the actual thumbnail of the actor or the nocover.gif (question mark image).
If the image is not showing something went wrong with either the img.php or the cache folder
Errors in the former can always be viewed by requesting the img.php directly
