### ISSUE TITLE
imdb trace.php-ing is broken (and probably can't be fixed)

### ISSUE THREAD

**Issue by johanneskonst** [andig/videodb#176]
I'm not a user of the trace.php functionality myself but have been "working" with it recently, and from what I can gather it is broken (and probably can't be fixed) because of all the JavaScript that's being used these days.

Even though I'm usually the first to say that everything can be fixed (in code) for this specific case that would probably mean not only proxying the IMDb html output but also all the JavaScript stuff, creating fix-ups for any errors that might arise because of the proxying, etc. and all that would gain us is (correct me if I'm wrong) an easy way to add movies to videoDB by browsing IMDb and clicking on a plus-sign here and there.

Wouldn't it then also be an option to remove the trace.php functionality (and thereby simplifying the code and maintenance of videoDB) and if needed replace that with some instructions on how to "share" an IMDb URL with your videoDB installation as to add a movie that way? Might even open up adding stuff through other engines...

Your thoughts please, thank you!

**Comment by copperhead57** [comment]
a strange one trace is working in nexgen template but not for other templates.
have family visiting over xmas weekend will look at when can.

**Comment by johanneskonst** [comment]
@copperhead57 no rush, family first ;-) happy holidays!

**Comment by copperhead57** [comment]
found some time to look at.
the text 'We are unable to load this content at this time. Please refresh the page or try again later.' appearing for all templates except nexgen maybe from the way our header element is being built with most of the header info from imdb not included in our header but in the body element and i think javascript is looking for at least one line in header `<meta name="next-head-count" content="99?">` 99 being variable.
i think newgen frame2 works as imdb header data is in the frames header element.
