### ISSUE TITLE
videodb doesn't work with PHP7

### ISSUE THREAD

**Issue by Boris-de** [andig/videodb#79]
There are some issues with the breaking changes in the newly release PHP7. A few of them were quite easy to solve because an error/warning-message was shouting at me :-)

But I'm currently stuck with an error on adding/editing videos, where all fields are empty when using PHP7, but without any obvious error. The think I tracked down the error to prepareSQL so far. Will try to have a look at it tomorrow again.

I'm collecting the changes at the php7-fixes branch in my fork: https://github.com/andig/videodb/compare/master...Boris-de:php7-fixes

**Comment by andig** [comment]
Hi Boris, I'm no longer actively developing videodb but please feel free to push a PR.

**Comment by Boris-de** [comment]
Hi Andi, fair enough, didn't know that yet. I wanted to create a PR with the changes anyway once I got rid of the last (obvious) breaking bug.
