### ISSUE TITLE
Cover Image Fetching / IMDB and Google / not working anymore

### ISSUE THREAD

**Issue by skillz-xx** [andig/videodb#81]
Hello

Since a couple of days I notice that the fetching of cover images from Google and (sometimes) als from IMDB does not work anymore..

I have the latest version of files installed and it used to work just fine a few weeks ago..

an example where IMDB has a coverimage, but videodb would not fetch: 
http://www.imdb.com/title/tt0099850/

another example where it HAS fetched ok:
http://www.imdb.com/title/tt0081182/

please help

thx

**Comment by jbjoret** [comment]
Same issue here. For instance Vanilla Sky in ImDB (0259711) won't fetch the cover picture.

**Comment by skillz-xx** [comment]
seems to happen all the time now. Obviously imdb changed its site structure and code again.
Can someone fix this? This would be highly appreciated!
cheers

**Comment by loudambiance** [comment]
I submitted a pull request that in my testing fixes this. It's a simple change that just needs updating one line in the imdb.php file in the engines directory. [Here](https://github.com/loudambiance/videodb/commit/23becca5b2dfa1cba4e69f7303caf321ec7ed23a) is the commit in my repo is  you want to apply to your file.

**Comment by skillz-xx** [comment]
super! thx! this worked just fine!
