### ISSUE TITLE
Borrow movie is incompatible with MySql 5.7

### ISSUE THREAD

**Issue by kec2** [andig/videodb#88]
Select a movie and click Borrow.

This is what borrow.php displays:

Database Problem

Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'videodb.videodb_videodata.subtitle' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by 
SELECT who, DATE_FORMAT(dt,'%d.%m.%Y') as dt, videodb_lent.diskid, CASE WHEN subtitle = '' THEN title ELSE CONCAT(title,' - ',subtitle) END AS title, videodb_videodata.id, COUNT(videodb_lent.diskid) AS count, videodb_users.name AS owner FROM videodb_lent, videodb_videodata LEFT JOIN videodb_users ON owner_id = videodb_users.id WHERE videodb_lent.diskid = videodb_videodata.diskid AND videodb_users.name = 'klaus' GROUP BY videodb_lent.diskid ORDER BY who, videodb_lent.diskid

**Comment by andig** [comment]
You can fix this by changing the sql_mode setting.

**Comment by andig** [comment]
Should be fixed thanks to @kec2
