### ISSUE TITLE
Fetching data not working anymore with IMDB 

### ISSUE THREAD

**Issue by miziomenca** [andig/videodb#96]
Help.
It seems that fetching data from imdb is completely down.

**Comment by jbjoret** [comment]
It has been about a week that it is not working for me either. :'(

**Comment by kec2** [comment]
I can't reach imdb.com at all.

**Comment by kec2** [comment]
IMDB.com is up again.

**Comment by andig** [comment]
I have not actively been maintaining videodb for a couple of years now (actually: it could use a rewrite on modern technology like Symfony and Bootstrap) but I'd be happy to accept PRs.

**Comment by jbjoret** [comment]
IMDB page is working. But as I said, now it redirects to https which the httpClient.php cannot handle. Using Bootstrap could be cool :). @andig sorry for my ignorance but what does Pos mean ? :)

**Comment by andig** [comment]
@jbjoret PR is a pull request- a contribution to this repo that you can make

as for `httpClient` it should be entirely replaced, e.g. by https://github.com/guzzle/guzzle

**Comment by kec2** [comment]
@andig Do you have any advice of how to "attack" the task of plugging Guzzle into VideoDB?
I guess that lib/ is the place to put Guzzle.

**Comment by andig** [comment]
I would start moving to composer: composer install it and add the /vendor folder to the repo. In httpclient inlcude vendor/autoload.php and use the guzzle classes. As I‘ve said- the codebase is severely outdated :(

**Comment by miziomenca** [comment]
I'm so sorry guys but i'm not a coder. I tried to study and understand Guzzle but.... sorry.
My entire collection (>2400 movies) is on my VideoDB forever.

**Comment by kec2** [comment]
I can try and look at it but I'm not making any promises.

**Comment by kec2** [comment]
I have upgraded httpclient.php with Guzzle. 
But i'm not able to create a pull request. I'm not sure if it is missing rights or skills. I'm using the GitHub desktop tool.

**Comment by andig** [comment]
You can email me your folder. 

Viele Grüße,
Andreas

**Comment by kec2** [comment]
Hi Andreas


The zip only contains files that I have modified or added.


Regards

Klaus Christiansen


________________________________

**Comment by andig** [comment]
Can you email me at cpuidle@gmx.de? No zip file received...

**Comment by olaf-d-aix** [comment]
Hi Andreas,
thanks for the quick fix. But it seems not to be complete.
Some data from IMDB can now be fetched again, mainly the pictures. If I open a movie right now, updating the actor images works again. Formerly it took bloody ages until a timeout occurs, so videodb hangs for a while.
But I'm not able to add a new movie! If I try that I get an error: "Server returned wrong status."
Is a simple "git pull" enough?

**Comment by andig** [comment]
You‘ll need to merge the pr for testing or checkout it‘s branch. 

Viele Grüße,
Andreas

**Comment by olaf-d-aix** [comment]
Finally I managed to get an "An exception occured: Server error: `GET http://www.imdb.com/find?q=test` resulted in a `503 Service Unavailable` response:" error.

**Comment by miziomenca** [comment]
So… sorry, i realy don't wanna be annoying but… nobody found a solution? There's no way?
I'm so sad for my inability to bring support about the problem.

**Comment by andig** [comment]
I've updated https://github.com/andig/videodb/pull/97 with the engine changes by @kec2 

@kec2 those were not mergeable and instead basically replaced the old files. Not sure why (e.g. imdb).  Please check if this works for you. In not I'd be happy to accept a PR to readme that this repo is no longer maintained and point to your.

**Comment by kec2** [comment]
Hi Andig,


I'm confident that imdb.php works. Maybe the fact the some files can't be merged is due to space/tab and/or different line endings.

The changes to the other engines are due to changes in httpClient.php. I have never used the other engines then IMDB, so I don't know if they work or not.


Hilsen

Klaus Christiansen


________________________________

**Comment by andig** [comment]
@kec2 seems it was the line endings. I've updated once again so it looks like a proper merge and would appreciate a test. All your changes plus some fixes to the http client should be inlcuded now. I've only done a superficial test though.

**Comment by copperhead57** [comment]
can anyone help - using 'GUZZLE' branch from andig and getting the following error.
An exception occurred:
cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Array ( [0] => Array ( [function] => exception_handler [file] => D:\web\wamp64\www\videodb-guzzle\core\functions.php [line] => 0 [params] => Array ( ) ) [1] => Array ( [function] => errorpage [file] => D:\web\wamp64\www\videodb-guzzle\core\functions.php [line] => 99 [params] => Array ( ) ) ) 

seems to be coming from file - D:\web\wamp64\www\videodb-guzzle\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php - line 176.

using php - 5.6.35.
thanks
Paul.

**Comment by andig** [comment]
@copperhead57 what are you trying to fetch when that happens?

**Comment by copperhead57** [comment]
@andig i am just clicking the imdb online tab to get the first screen displayed.

will review look into php/curl etc tomorrow

**Comment by copperhead57** [comment]
@andig success (well mostly)
 - firstly Curl error 60 fixed with following steps
- ensure ssl_module in apache is active
- ensure php_openssl is active
- download cacert.pem from https://curl.haxx.se/docs/caextract.html to directory D:\web\wamp64\bin\php\php5.6.35\extras\ssl\
- update php.ini file [openssl] with openssl.cafile= "D:\web\wamp64\bin\php\php5.6.35\extras\ssl\cacert.pem"
- restart all services.
have been able to add new movie from pulling from IMDB from the 'new' tab
