### ISSUE TITLE
Plot not being saved from imdb on add or update

### ISSUE THREAD

**Issue by copperhead57** [andig/videodb#99]
In Guzzle branch plot not being saved for add or update.
I am not sure how to use GitHub for suggested fixes but I have the following fix which seems to work'
I have made a change in imdb.php at line 325.
old code
 
` preg_match('/<h2>Storyline<\/h2>.*?<p>(.*?)</si', $resp['data'], $ary); ` 
new code 
  `    preg_match('/<h2>Storyline<\/h2>.*?<p>(.*?)<\/sp/si', $resp['data'], $ary);` 
 regards
Paul.

**Comment by andig** [comment]
Mhhm- these two regexes should be equivalent?

**Comment by copperhead57** [comment]
@andig as i see it (i could be wrong)
the new code has string to be matched terminating at `</span>` old code terminated at the end  span element. the first > after `<p>`.
 
`<h2>Storyline</h2>        
        <div class="inline canwrap">
            <p>
                <span itemprop="description">    Starr........of love.</span>`

**Comment by andig** [comment]
Fixed via f1dff15179894796283adc45580c9a6d01c1d320, thanks for the clarification!
